site_name: Docs
site_description: Documentation for the Cognitive Automation Labs platform
nav:
  - 'Overview': 
      - index.md
      - 'About us': home/about.md
      - 'Contributions': home/contributions.md
      - 'Contact us': home/contact.md
  - 'Insight':
      - insight/index.md
      - 'Getting started': insight/1_getting_started.md
      - 'Installation': insight/2_installation.md
      - 'Configuration': insight/3_configuration.md
  - 'Monitor':
      - monitor/index.md
      - 'Getting started': monitor/1_getting_started.md
      - 'Installation': monitor/2_installation.md
      - 'Configuration': monitor/3_configuration.md

theme:
  name: material
  # custom_dir: overrides
  logo: img/favicon/cal-fav.png
  favicon: img/favicon/cal-fav.png
  font:
    text: Sora
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.footer


  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      theme:
        logo: img/logo/ca-labs-logo-master.png
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      theme:
        logo: img/logo/ca-labs-logo-white.png
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cognitive-automation-labs/
    - icon: material/email
      link: https://cognitiveautomationlabs.com/contact
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - toc:
      title: Contents
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# copyright: |
#   &copy; 2023 <a href="https://cognitiveautomationlabs.com/"  target="_blank" rel="noopener">Cognitive Automation Labs</a>
